=== ministryofjustice/opg-data-lpa/integration_tests/v1/response_schemas/use_an_lpa_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "uId": {
      "type": "string"
    },
    "receiptDate": {
      "type": ["string", "null"]
    },
    "registrationDate": {
      "type": ["string", "null"]
    },
    "rejectedDate": {
      "type": ["string", "null"]
    },
    "donor": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "uId": {
          "type": "string"
        },
        "dob": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "salutation": {
          "type": "string"
        },
        "firstname": {
          "type": "string"
        },
        "otherNames": {
          "type": ["string", "null"]
        },
        "middlenames": {
          "type": ["string", "null"]
        },
        "surname": {
          "type": "string"
        },
        "addresses": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "town": {
                  "type": "string"
                },
                "county": {
                  "type": "string"
                },
                "postcode": {
                  "type": "string"
                },
                "country": {
                  "type": "string"
                },
                "type": {
                  "type": "string"
                },
                "addressLine1": {
                  "type": "string"
                },
                "addressLine2": {
                  "type": "string"
                },
                "addressLine3": {
                  "type": "string"
                }
              },
              "required": [
                "id",
                "town",
                "county",
                "postcode",
                "country",
                "type",
                "addressLine1",
                "addressLine2",
                "addressLine3"
              ]
            }
          ]
        },
        "companyName": {
          "type": "null"
        }
      },
      "required": [
        "id",
        "uId",
        "dob",
        "email",
        "salutation",
        "firstname",
        "otherNames",
        "middlenames",
        "surname",
        "addresses",
        "companyName"
      ]
    },
    "applicationType": {
      "type": "string"
    },
    "caseSubtype": {
      "type": "string"
    },
    "status": {
      "type": "string"
    },
    "caseAttorneySingular": {
      "type": "boolean"
    },
    "caseAttorneyJointlyAndSeverally": {
      "type": "boolean"
    },
    "caseAttorneyJointly": {
      "type": "boolean"
    },
    "caseAttorneyJointlyAndJointlyAndSeverally": {
      "type": "boolean"
    },
    "onlineLpaId": {
      "type": ["string", "null"]
    },
    "cancellationDate": {
      "type": ["string", "null"]
    },
    "attorneys": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "uId": {
              "type": "string"
            },
            "dob": {
              "type": "string"
            },
            "email": {
              "type": "string"
            },
            "salutation": {
              "type": "string"
            },
            "firstname": {
              "type": "string"
            },
            "otherNames": {
              "type": ["string", "null"]
            },
            "middlenames": {
              "type": ["string", "null"]
            },
            "surname": {
              "type": "string"
            },
            "addresses": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "town": {
                      "type": "string"
                    },
                    "county": {
                      "type": "string"
                    },
                    "postcode": {
                      "type": "string"
                    },
                    "country": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    },
                    "addressLine1": {
                      "type": "string"
                    },
                    "addressLine2": {
                      "type": "string"
                    },
                    "addressLine3": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "town",
                    "county",
                    "postcode",
                    "country",
                    "type",
                    "addressLine1",
                    "addressLine2",
                    "addressLine3"
                  ]
                }
              ]
            },
            "systemStatus": {
              "type": "boolean"
            },
            "companyName": {
              "type": ["string", "null"]
            }
          },
          "required": [
            "id",
            "uId",
            "dob",
            "email",
            "salutation",
            "firstname",
            "otherNames",
            "middlenames",
            "surname",
            "addresses",
            "systemStatus",
            "companyName"
          ]
        }
      ]
    },
    "replacementAttorneys": {
      "type": "array",
      "items": {}
    },
    "trustCorporations": {
      "type": "array",
      "items": {}
    },
    "certificateProviders": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "uId": {
              "type": "string"
            },
            "dob": {
              "type": "null"
            },
            "email": {
              "type": "null"
            },
            "salutation": {
              "type": "string"
            },
            "firstname": {
              "type": "string"
            },
            "otherNames": {
              "type": ["string", "null"]
            },
            "middlenames": {
              "type": ["string", "null"]
            },
            "surname": {
              "type": "string"
            },
            "addresses": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "town": {
                      "type": "string"
                    },
                    "county": {
                      "type": "string"
                    },
                    "postcode": {
                      "type": "string"
                    },
                    "country": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    },
                    "addressLine1": {
                      "type": "string"
                    },
                    "addressLine2": {
                      "type": "string"
                    },
                    "addressLine3": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "town",
                    "county",
                    "postcode",
                    "country",
                    "type",
                    "addressLine1",
                    "addressLine2",
                    "addressLine3"
                  ]
                }
              ]
            }
          },
          "required": [
            "id",
            "uId",
            "dob",
            "email",
            "salutation",
            "firstname",
            "otherNames",
            "middlenames",
            "surname",
            "addresses"
          ]
        }
      ]
    },
    "attorneyActDecisions": {
      "type": "null"
    },
    "applicationHasRestrictions": {
      "type": "boolean"
    },
    "applicationHasGuidance": {
      "type": "boolean"
    },
    "lpaDonorSignatureDate": {
      "type": "string"
    },
    "lifeSustainingTreatment": {
      "type": ["string", "null"]
    },
    "lpaIsCleansed": {
      "type": "boolean"
    }
  },
  "required": [
    "id",
    "uId",
    "receiptDate",
    "registrationDate",
    "rejectedDate",
    "donor",
    "applicationType",
    "caseSubtype",
    "status",
    "caseAttorneySingular",
    "caseAttorneyJointlyAndSeverally",
    "caseAttorneyJointly",
    "caseAttorneyJointlyAndJointlyAndSeverally",
    "onlineLpaId",
    "cancellationDate",
    "attorneys",
    "replacementAttorneys",
    "trustCorporations",
    "certificateProviders",
    "attorneyActDecisions",
    "applicationHasRestrictions",
    "applicationHasGuidance",
    "lpaDonorSignatureDate",
    "lifeSustainingTreatment",
    "lpaIsCleansed"
  ]
}

=== ministryofjustice/opg-data-lpa/lambda_functions/v1/tests/test_data/use_an_lpa_successful_response.json
{
    "applicationHasGuidance": false,
    "applicationHasRestrictions": false,
    "applicationType": "Classic",
    "attorneyActDecisions": null,
    "attorneys": [
        {
            "addresses": [
                {
                    "addressLine1": "25 Cambridge Road",
                    "addressLine2": "CHATTERIS",
                    "addressLine3": "",
                    "country": "",
                    "county": "",
                    "id": 7,
                    "postcode": "PE4 7DH",
                    "town": "",
                    "type": "Primary"
                }
            ],
            "companyName": null,
            "dob": "1972-05-10",
            "email": "bodge@example.com",
            "firstname": "Trevor",
            "otherNames": null,
            "id": 7,
            "middlenames": null,
            "salutation": "Mr",
            "surname": "Bodger",
            "systemStatus": true,
            "uId": "7000-0000-0104"
        }
    ],
    "cancellationDate": null,
    "caseAttorneyJointly": false,
    "caseAttorneyJointlyAndJointlyAndSeverally": false,
    "caseAttorneyJointlyAndSeverally": true,
    "caseAttorneySingular": false,
    "caseSubtype": "pfa",
    "certificateProviders": [
        {
            "addresses": [
                {
                    "addressLine1": "32 Jamestown Street",
                    "addressLine2": "ABLEFIELD",
                    "addressLine3": "",
                    "country": "",
                    "county": "",
                    "id": 5,
                    "postcode": "AB2 8KJ",
                    "town": "",
                    "type": "Primary"
                }
            ],
            "dob": null,
            "email": null,
            "firstname": "Julian",
            "otherNames": null,
            "id": 5,
            "middlenames": null,
            "salutation": "Mr",
            "surname": "Salford",
            "uId": "7000-0000-0088"
        }
    ],
    "donor": {
        "addresses": [
            {
                "addressLine1": "lxzraboqaxnygvbfnbcrdozklqfzpsycwegllkkuubywvvyvjj",
                "addressLine2": "SOLLINGSBURY",
                "addressLine3": "",
                "country": "",
                "county": "",
                "id": 1,
                "postcode": "cytxlxdequ",
                "town": "",
                "type": "Primary"
            }
        ],
        "companyName": null,
        "dob": "1952-07-17",
        "email": "sally.fathing@opgtest.com",
        "firstname": "changeme",
        "otherNames": "Lucy",
        "id": 1,
        "middlenames": "Lucille",
        "salutation": "Mrs",
        "surname": "changeme",
        "uId": "7000-0000-0047"
    },
    "id": 1,
    "lifeSustainingTreatment": null,
    "lpaIsCleansed": true,
    "lpaDonorSignatureDate": "2020-07-15",
    "onlineLpaId": null,
    "receiptDate": "2014-09-26",
    "registrationDate": null,
    "rejectedDate": null,
    "replacementAttorneys": [],
    "status": "Pending",
    "trustCorporations": [
        {
            "addresses": [
                {
                    "addressLine1": "170 High Street",
                    "addressLine2": "Oxford",
                    "addressLine3": "Oxfordshire",
                    "country": "",
                    "county": "",
                    "id": 6,
                    "postcode": "OX1 1XO",
                    "town": "",
                    "type": "Primary"
                }
            ],
            "companyName": "TrustyLaw.com",
            "dob": null,
            "email": "",
            "firstname": null,
            "otherNames": null,
            "id": 6,
            "middlenames": null,
            "salutation": null,
            "surname": null,
            "systemStatus": false,
            "uId": "7000-0000-0096"
        }
    ],
    "uId": "7000-0000-0013"
}
